# Generated by Django 4.0.4 on 2022-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='link',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
